
    * What are the four steps a processor performs in executing a single
      instruction?

    * The processor uses something called a ``program counter``  (or
      ``instruction pointer``) to track where
      the next instruction to process can be found. How is this counter
      updated?

    * We see the term "virtual machine" a lot in the computer industry these
      days. What is a virtual machine?

    * A processor is driven by a clock and performs four steps during wach
      "tick" Show a fragment of C/C++ code that models this behavior.

    * What do we mean when we say the machine has a "state" at any moment in time?

    * Why are "registers" included in the design of a processor?

    * What is contained in an executable file, and what tool places that file
      into memory?

    * What is the difference between a Von Neumann machine and a Harvard Machine?

    * Describe the signals (data and any other things) needed by the ALU to do its job.

