    * (Challenge) Using our four step instruction processing pattern, how might
      we cause the processor to fetch the next instruction from some other
      place in memory, instead of the next instruction in memory (the
      instruction would look like this: JUMP address) 

    
    * Suppose you have a file containing source code for a C++ program. What
      are the fundamental tools you need to activate to get this code actually
      running on a computer? Be sure to indicate what each tool produces.
