
    * Computers are constructed out of basic components interconnected
      by signals. What kinds of signals do we find moving between these
      components?

    * What is a "multiplexor"?

    * What is a "demultiplexor"?

    * Draw a digram of a basic ALU component showing the signals needed
      to make it work.

    * If a machine needs to send data into one side of the ALU from internal
      registers, external memory, or a constant contained in the
      Instruction Register, how would we hook things up to feed those
      signals? (You only need to show the ALU and incoming signals, not
      the devices where those data originate.)

    * Why do chip designers make it possible to read from two internal
      registers simultaneously?

    * Show how memory is connected to the control unit.

    * What is a "wait state" and why is it needed?

    * Basically, how is decoding of an instruction accomplished?

..  vim:filetype=rst spell:
