
    * What is a "Register Transfer Language?

    * In the old days, chip designers spent most of their time drawing
      complex circuit diagrams. Why did this change to focusing on
      "register Transfer Language"

    * Show an example of using RTL to move data from the system memory
      to an internal register.

    *  There are four basic classes of instructions in a processor. One
       is simple movement of data between places in the machine.
       What are the other three? (Think Von Neumann!)

    * How can RTL be used to study the timing of signals in a computer?

..  vim:filetype=rst spell:

