
    * Can you define most of the internal registers needed by each
      component in the Von Neumann Machine?

    * We can connect all of the internal components using a single
      "common bus" interconnect system. What impact does this have on
      system performance?

    * Consider a machine with an instruction like this:

      .. code-block:: text
         
         MOV  SRC, DEST

      For the Pentium, what locations in the system  can SRC and DEST refer to?
 
..  vim:filetype=rst spell:


