Learning Outcomes/Course Objectives:
====================================

   1.  Explain contemporary computer system organization.

   2.  Describe data representation in digital computers.
    
   3.  Explain the concepts of memory hierarchy, interrupt processing, and input/output mechanisms.

   4.  Measure the performance of a computer system.

   5.  Design and develop assembly language applications.

   6.  Explain the interfaces between software and hardware components.

   7.  Explain the design of instruction set architectures.

   8.  Develop a single - cycle processor.

   9.  Explain the concept of virtual memory and how it is realized in hardware and software.

   10.  Explain the concepts of operating system virtualization

..  note::

    In this course, we will also explore tools all modern developers should be
    able to use. Specifically, we will use `virtual machines` and `source code
    control systems` for class projects.
