Course Description:
===================

The organization of computer systems is introduced using assembly language.
Topics include basic concepts of computer architecture and organization, memory
hierarchy, data types, computer arithmetic, control structures, interrupt
handling, instruction sets, performance metrics, and the mechanics of testing
and debugging computer systems. Embedded systems and device interfacing are
introduced
