Instructional Methodology:
==========================

This course will have 2.4 hours of lecture and 2 hours of lab per week. If
the students are unable to finish the assigned lab work within the lab time,
they will need to visit the CIS open labs. Teaching methodology will be to use
a hybrid approach utilizing traditional in-class lectures and lab sessions
coupled with distance-learning techniques utilizing computers and the
Internet. The students will be expected to use the lab workstations for all
homework submissions. Submission techniques will be taught during the first
few lectures. No homework will be accepted through any submission channel
except through the class lab workstations! Exams will be given in class.
